[tool.poetry]
name = "terminal-print"
version = "0.3.5"
authors = [
    "Haixuan Xavier Tao <tao.xavier@outlook.com>",
    "Enzo Le Van <dev@enzo-le-van.fr>",
]
description = "Dora Terminal Print"
license = "MIT License"
homepage = "https://github.com/dora-rs/dora.git"
readme = "README.md"
packages = [{ include = "terminal_print" }]

[tool.poetry.dependencies]
dora-rs = "0.3.5"
numpy = "< 2.0.0"
pyarrow = ">= 5.0.0"

[tool.poetry.scripts]
terminal-print = "terminal_print.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"

[project]
readme = "README.md"
