[package]
name = "dora-operator-api-cxx"
version.workspace = true
edition = "2021"
documentation.workspace = true
description.workspace = true
license.workspace = true

[lib]
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0.73"
dora-operator-api = { workspace = true }

[build-dependencies]
cxx-build = "1.0.73"
