[package]
name = "dora-tracing"
version.workspace = true
edition = "2021"
license = "Apache-2.0"
documentation.workspace = true
description.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opentelemetry = { version = "0.17", features = ["rt-tokio", "metrics"] }
opentelemetry-jaeger = { version = "0.16", features = ["rt-tokio"] }
tokio = { version = "1.24.2", features = ["full"] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
eyre = "0.6.8"
tracing = "0.1.36"
