[package]
name = "dora-cli"
version.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "dora-cli"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0.3", features = ["derive"] }
eyre = "0.6.8"
dora-core = { path = "../../libraries/core" }
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.9.11"
tempfile = "3.3.0"
webbrowser = "0.8.0"
serde_json = "1.0.86"
termcolor = "1.1.3"
atty = "0.2.14"
uuid = { version = "1.2.1", features = ["v4", "serde"] }
inquire = "0.5.2"
communication-layer-request-reply = { path = "../../libraries/communication-layer/request-reply" }
duration-str = "0.5"
