[package]
name = "dora-node-api-c"
version.workspace = true
edition = "2021"

documentation.workspace = true
description.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]

[features]
default = ["tracing"]
tracing = ["dora-node-api/tracing"]

[dependencies]
eyre = "0.6.8"
flume = "0.10.14"
tracing = "0.1.33"

[dependencies.dora-node-api]
workspace = true
