[package]
name = "communication-layer-pub-sub"
version.workspace = true
edition = "2021"

[features]
default = ["zenoh"]
zenoh = ["dep:zenoh"]

[dependencies]
zenoh = { version = "0.7.0-rc", optional = true, features = ["transport_tcp"] }
flume = "0.10"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
