[package]
name = "shared-memory-server"
version.workspace = true
edition = "2021"
license = "Apache-2.0"
documentation.workspace = true
description.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
serde = { version = "1.0.152", features = ["derive"] }
shared_memory = "0.12.0"
# TODO use upstream release once https://github.com/elast0ny/raw_sync-rs/pull/29 is merged
raw_sync = { git = "https://github.com/cameronelliott/raw_sync-rs.git" }
bincode = "1.3.3"
tracing = "0.1.37"
