[tool.poetry]
name = "dora-qwenvl"
version = "0.3.6-rc0"
authors = [
    "Haixuan Xavier Tao <tao.xavier@outlook.com>",
    "Enzo Le Van <dev@enzo-le-van.fr>",
]
description = "Dora Node for VLM"
readme = "README.md"

packages = [{ include = "dora_qwenvl" }]

[tool.poetry.dependencies]
python = "^3.7"
dora-rs = "^0.3.6"
numpy = "< 2.0.0"
torch = "^2.4.0"
torchvision = "^0.19"
transformers = { git = "https://github.com/huggingface/transformers" }
qwen-vl-utils = "^0.0.2"
accelerate = "^0.33"
flash-attention = "^2.6.1"


[tool.poetry.scripts]
dora-qwenvl = "dora_qwenvl.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
