[package]
name = "dora-node-api-cxx"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0.73"
dora-node-api = { version = "0.1.1", path = "../../../apis/rust/node", default-features = false, features = [
    "zenoh",
] }
eyre = "0.6.8"

[build-dependencies]
cxx-build = "1.0.73"
