[package]
name = "dora-download"
version.workspace = true
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
reqwest = { version = "0.11.12", default-features = false, features = [
    "rustls",
] }
tokio = { version = "1.24.2" }
tracing = "0.1.36"
