name: CI-python

# Filter CI as this job will take time.
on:
  push:
    paths:
      - apis/python/**
      - binaries/runtime/**
  pull_request:
  workflow_dispatch:

jobs:
  examples:
    name: "Python Examples"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - uses: r7kamura/rust-problem-matchers@v1.1.0
      - run: cargo --version --verbose
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "ubuntu-latest"

      - name: "Python Dataflow example"
        run: cargo run --example python-dataflow

      - name: "Python Operator Dataflow example"
        run: cargo run --example python-operator-dataflow
